- name: Run Docker container on QA Node
  hosts: qa
  become: true
  tasks:
    - name: Stop existing container (if running)
      docker_container:
        name: html-css-web
        state: absent
        force_kill: true

    - name: Run new container
      docker_container:
        name: html-css-web
        image: html-css-web:latest
        state: started
        ports:
          - "8080:80"
        restart_policy: always
